### ISSUE TITLE
Magento 2.3.3 compatibility problem

### ISSUE THREAD

**Issue by maximecarey** [Dan0sz/ResourceHints-magento2#1]
Trying to install on Magento 2.3.3 and I'm getting this exception:

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/var/www/html/vendor/dan0sz/resource-hints-magento2/etc/adminhtml/system.xml" is invalid:
Element 'class': This element is not expected.
Line: 15

**Comment by Dan0sz** [comment]
Hi @werfu!

Thanks for giving my extension a try! This issue has been resolved in v1.0.1.
