### ISSUE TITLE
Optimization points

### ISSUE THREAD

**Issue by in-session** [Dan0sz/ResourceHints-magento2#13]
hi thanks first for the great module

I would still have a few points which one could perhaps still implement.
An additional text field to insert own data inside the link would be super.

As an example for fonts additional part: 
{name="Rubik" as="font" weight="300" type="font/woff2"}

`<link  rel="preload" as="font" href="...../fonts/rubik-v12-latin-300.woff2" />`
`<link  rel="preload" as="font" name="Rubik" as="font" weight="300" type="font/woff2" href="...../fonts/rubik-v12-latin-300.woff2" />`

or images:
{ type="image/webp" media="all"}
`<link rel="preload" href="....logo.svg" as="image" />`
`<link rel="preload" type="image/webp" media="all" href="....logo.svg" as="image" />`

Also I noticed that the links are output after the CSS in the header, it would be better to add this relatively high up before the regular CSS data or directly after the </title> of the page
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload#the_basics

**Comment by Dan0sz** [comment]
Hi!

Feel free to submit a pull request with the additions. :) I'm not actively maintaining this extension anymore. Sorry!

**Comment by Leland** [comment]
> Also I noticed that the links are output after the CSS in the header, it would be better to add this relatively high up before the regular CSS data

I brought this up in #9 – the [preloader in browsers](https://andydavies.me/blog/2013/10/22/how-the-browser-pre-loader-makes-pages-load-faster/) is smarter than we give it credit for and successfully navigates this. It may trip over itself if there's a HUGE amount of e.g. critical CSS data in the head :)
