### ISSUE TITLE
Update / Delete PHP version requirement?

### ISSUE THREAD

**Issue by pmonosolo** [Dan0sz/ResourceHints-magento2#15]
Howdy, 

can you please remove or update the PHP version requirement? Magento 2.4.5 just came out and it doesnt allow me to install on PHP 8.1

Thanks!

**Comment by TweetyBoop1990** [comment]
I 2nd this!!

**Comment by rossmc** [comment]
I 3rd this!!!
<img width="868" alt="CleanShot 2022-11-01 at 11 36 50@2x" src="https://user-images.githubusercontent.com/2452991/199224514-0b907913-e8d5-486b-ae33-051bb61e1702.png">

**Comment by Dan0sz** [comment]
Have you tried running it with the `--ignore-platform-reqs` flag? That should do it.

**Comment by rossmc** [comment]
Thanks for merging @Dan0sz , can you tag it on GitHub please too, I think that's required for us to be able to install latest version with composer

I haven't used `--ignore-platform-reqs`, but I avoid using that for production environments

**Comment by Dan0sz** [comment]
Hi, sorry for the late reply. I've removed the Magento version requirements in composer.json as well, and have tagged it v1.2.1. I checked and its available on Packagist.org, so you should be able to install it.
