### ISSUE TITLE
addRemotePageAsset - will this add new resource?

### ISSUE THREAD

**Issue by VivekShingala** [Dan0sz/ResourceHints-magento2#3]
hi @Dan0sz 

Thank you for this awesome plugin. However, I have a question that will the method addRemotePageAsset add a new resource to the page or update the properties of existing loaded font or style?

Let say, my theme has 8 fonts loading already and I want to preload it. If I add all those URLs through this extension, will it update already loading fonts or it will add extra entries to load fonts?

**Comment by tig-daanvandenbergh** [comment]
Hi @VivekShingala,

I suggest you read into how the `preload` attribute works, because it does not add extra resources. It preloads existing resources.

**Comment by Dan0sz** [comment]
Hi, @VivekShingala,

I suggest you read into how the `preload` attribute works. This attribute does not add extra resources, but preloads existing resources.
