### ISSUE TITLE
Check that you are using the `crossorigin` attribute properly.

### ISSUE THREAD

**Issue by wecode-apps** [Dan0sz/ResourceHints-magento2#5]
Warnings: A preload <link> was found for "xxxxxx" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.

is there an option to add crossorigin ?

**Comment by Dan0sz** [comment]
Hi @wecode-apps,

I just updated the extension, and it now supports the `crossorigin` attribute! 

Enjoy! 🥳
