### ISSUE TITLE
Static asset signing support

### ISSUE THREAD

**Issue by Leland** [Dan0sz/ResourceHints-magento2#7]
Magento 2 by default ["signs" static assets](**https://devdocs.magento.com/guides/v2.4/config-guide/cache/static-content-signing.html**) like so:

`http://magento2.com/static/version1603919135/frontend/Magento/blank/en_US/fonts/Blank-Theme-Icons/Blank-Theme-Icons.woff2`

This makes it tricky to preload any theme assets - that version value changes over time, so we can't express it in this extension's URL entry.

It would be great to have support for that hash in the extension. Perhaps the extension should silently insert it for any relative URLs, or any URL that matches the root URL + static || pub/static?

**Comment by Dan0sz** [comment]
Hi @Leland,

The version signing only happens in developer mode. On a production environment this shouldn't be the case. If it does, then you should disable it, because it prevents your visitors from caching your static content, thus it degrades performance.

`bin/magento config:set dev/static/sign 0`

**Comment by Leland** [comment]
Hey @Dan0sz! Can't say I agree - caching still happens normally under asset signing.

It's simply a method to cache bust following a deployment, ensuring that visitors aren't, for instance, seeing an outdated CSS file.

From [Magento's own docs](https://devdocs.magento.com/guides/v2.4/config-guide/cache/static-content-signing.html):

> When the browser caches a static resource and that resource changes on the server, you need to clear the browser cache so it can download the new version. Manually clearing the browser cache works if you are a website administrator, but this is not an appropriate request to make of your users when you want them to download new versions of a static resource.

> Static content signing is a Magento feature that allows you to invalidate the browser cache for static resources. Magento accomplishes this by adding a deployment version to the URL of static files.

This feature is enabled by default, so most M2 sites have it on – which is a best practice IMO, and so a good thing 😀

> The version signing only happens in developer mode

The reverse is true, actually – static content signing is only for production mode! Since the version number is derived from `setup:static-content:deploy`, and that command is disabled in developer mode, it wouldn't be of much use on a local env.

Hope you reconsider this issue!

**Comment by Dan0sz** [comment]
Hm. Suppose you're right. I'll have to look into this and get back to you!

**Comment by chedaroo** [comment]
@Dan0sz Thanks for making this available

#8 should resolve for all environments, all assets passed are assumed to be local now, unless otherwise specified, and will be resolved as such.

Hopefully my updates to the docs will be enough to explain the change.

**Comment by tig-daanvandenbergh** [comment]
@chedaroo and @Leland, I just released v1.2.0 which includes @chedaroo's PR! Enjoy :) And thanks!

**Comment by Leland** [comment]
Thanks all!
